### ISSUE TITLE
No TS error upon Document instantiation

### ISSUE THREAD

**Issue by barakbd** [szokodiakos/typegoose#142] opened 2018-04-27 18:07 UTC
Schema:
```
import { mongooseConnection } from "../config/mongoose_connection";

import { prop, Typegoose, ModelType, InstanceType } from "typegoose";

export class Collaboration extends Typegoose {
  @prop({ required: true })
  user_email: string;

  @prop({ required: true })
  item_id: string;

  @prop({ required: true })
  metadata: any;
} //end class File

const CollaborationModel: ModelType<Collaboration> = new Collaboration().getModelForClass(Collaboration, {
  existingConnection: mongooseConnection
});

export { CollaborationModel };
```

Query
```
CollaborationModel.find({
  user_email: req.params.user_email,
  item_id: req.params.item_id,
  non_existing_key: ""
});
```

I don't get an TS error for non_existing_key.

Same thing for creating a new document:
Does not show TS error:
```
let newCollaboration: InstanceType<Collaboration> = new CollaborationModel({non_existing_key: ""});
```
Shows TS error
```
let newCollaboration: InstanceType<Collaboration> = new CollaborationModel();

newCollaboration.non_existing_key = "";
```

**Comment by barakbd** [comment] 2018-04-27 18:08
IS it possible that a class constructor can help with this?

**Comment by hasezoey** [comment] 2019-05-25 05:45
Current workaround (that i found & use):
```ts
CollaborationModel.find({
  user_email: req.params.user_email,
  item_id: req.params.item_id,
  non_existing_key: ""
} as Collaboration);
```

but still, it would be good to have it automaticly, i would say it is a "bug"

**Comment by hasezoey** [comment] 2019-09-10 05:59
this cannot be fixed in typegoose itself, because typegoose aims to be a wrapper for models & schemas, but dosnt want to modify any functionality after it, so "by design" this will not be fixed

@Ben305 this can be closed as "not an issue with typegoose"

**Closed** 2019-09-10 14:21 UTC
