### ISSUE TITLE
serverless-webpack/webpack production mode problems

### ISSUE THREAD

**Issue by andreialecu** [szokodiakos/typegoose#242] opened 2019-02-08 21:04 UTC
I'm using typegoose with serverless-webpack and when compiling for production mode with minification enabled the following errors occur:

```
TypeError: Cannot convert undefined or null to object
at Function.keys ()
```

Related issues:
https://github.com/szokodiakos/typegoose/issues/207
https://github.com/szokodiakos/typegoose/issues/91

However, note that

```
optimization: {
  // We no not want to minimize our code.
  minimize: false
},
```

In web.config make the errors go away, but the results from mongoose are erratic. `SomeModel.find()` for example returns no results if webpack is in production mode. The only way to get it to work is to explicltly set `mode: 'none'` in webpack.config. 

The documentation for `serverless-webpack` suggests `mode: slsw.lib.webpack.isLocal ? "development" : "production",` by default, which causes problems for typegoose.

I'm not sure if this can be fixed otherwise, or should just be mentioned in the readme.

Just a heads-up for anyone that may be stuck on this.

**Comment by richarddd** [comment] 2019-06-25 10:51
I ran into this problem as well, could be solved by using another minimizer in your webpack config (which keeps classnames)

```
 optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        cache: true,
        // sourceMap: true,
        terserOptions: {
          ecma: 8,
          keep_classnames: true,
          keep_fnames: true,
        },
      }),
    ],
  },
```

**Comment by hasezoey** [comment] 2019-06-25 12:32
@andreialecu i know this issue is old, and if you still use it or try to, could you try to use [this repo](https://gitlab.com/hasezoey/typegoose) and say if this works with `minimize: true`?

or @richarddd could you try it too with the default minimizer?

PS: i dont know anything about webpack & serverless

**Comment by richarddd** [comment] 2019-06-27 04:54
@hasezoey the issue is that the default minimizer obfuscates class names which are required by typegoose to work. Sure, you could configure the default minimizer to keep class names as well but Terser is much more optimized and easy to use. Just install it as a dev dependency:

`yarn add terser-webpack-plugin --dev`

and import to webpack config:

`const TerserPlugin = require("terser-webpack-plugin")`

...and use the config above :)

**Comment by hasezoey** [comment] 2019-06-27 18:55
thanks for the clarification, because like i said, "i dont know anything about webpack & serverless"

**Comment by richarddd** [comment] 2019-07-03 03:56
@hasezoey nope you could use `mimimize: false` or change the minimizer config. This issue could be closed as it has nothing to do with typegoose :)

**Comment by hasezoey** [comment] 2019-07-27 20:08
@Ben305 this can probably be closed like described in the last comments...

**Closed** 2019-07-27 20:11 UTC
