### ISSUE TITLE
arrayProp problem

### ISSUE THREAD

**Issue by ManuRodgers** [szokodiakos/typegoose#288] opened 2019-05-24 23:45 UTC
how to achieve something like this with arrayProp

 tokens: [{
        token: {
            type: String,
            required: true
        }
    }]

**Comment by hasezoey** [comment] 2019-05-25 02:20
what do you want to achieve?
this:?
```ts
class Token {
    @prop({ required: true })
    public token!: string;
}

class Tokens extends Typegoose {
    @prop({ required: true, index: true })
    public id!: ObjectID;

    @arrayProp({ required: true, items: Token })
    public items!: Token[];
}
```

**Comment by ManuRodgers** [comment] 2019-05-25 05:12
thank you mate, even it is not exactly what I want, but your code gives me some hint and solved my issue.

**Comment by hasezoey** [comment] 2019-05-25 22:01
@ManuRodgers is your issue fully solved? when yes, you can close it now, or clarify what you mean/want, thanks

**Comment by Drageaux** [comment] 2019-05-31 22:54
```
tokens: [{
  token: {
    type: String,
    required: true
  }
}]
```
So is there an outer class contains the `token` property?

**Comment by hasezoey** [comment] 2019-06-01 00:39
@Drageaux how would you mean it?
-> the document is `Tokens` and the array (name `items`) is `Token[]`

**Comment by hasezoey** [comment] 2019-07-17 12:01
because of no activity, and it seems like the issue is solved by @ManuRodgers, i consider it closed 
@Ben305

**Comment by hasezoey** [comment] 2019-09-08 10:02
@Ben305 Bump to close

**Closed** 2019-09-09 19:03 UTC
