### ISSUE TITLE
recursive nested object error

### ISSUE THREAD

**Issue by naivefun** [szokodiakos/typegoose#132] opened 2018-04-06 11:33 UTC
With a treenode example:
```typescript
class Node {
  @prop()
  name: string;
  @arrayProp({ items: Node})
  children: Node[];
}
```

Here is the error:
```bash
exports.clone = function clone(obj, options) {
                              ^

RangeError: Maximum call stack size exceeded
```

**Comment by hasezoey** [comment] 2019-09-20 10:53
@Ben305 Duplicate of #19

**Closed** 2019-09-20 12:50 UTC
