### ISSUE TITLE
Only initialized variables and constants can be referenced in decorators

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#174] opened 2018-07-31 00:20 UTC
cannot compile my models for PRODUCTION

angular 6
RxJS 6

ng build --aot --prod

ERROR in src\server\model\app\App.ts(4,2): Error during template compile of 'App'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'pre'
    'pre' references 'pre'
      'pre' is not initialized at typegoose\lib\hooks.ts(3,22).

any tips on solution?

```

import {pre, prop, Typegoose} from 'typegoose'
import * as mongoose from 'mongoose'

@pre<App>('save', (next) => {
    if (!this.createdAt) {
        this.createdAt = this.updatedAt = new Date()
    }
    next()
})
export class App extends Typegoose {

    @prop()
    _id?: mongoose.Types.ObjectId

    @prop({required: true})
    name: string


    @prop()
    owner?: mongoose.Types.ObjectId

    @prop()
    createdAt?: Date
    @prop()
    updatedAt?: Date
}

export const model = new App().getModelForClass(App, {schemaOptions: {collection: 'app'}})



```

**Comment by nhhockeyplayer** [comment] 2018-09-14 16:12
Can someone take a look at this ?
I have been in hooks.ts line 21 and trying various attempts without resolve

all is needed is simple angular app that compiles a pojo

any assistance is appreciated

**Comment by nhhockeyplayer** [comment] 2018-09-25 01:44
https://github.com/angular/angular/issues/23713

**Comment by nhhockeyplayer** [comment] 2018-10-02 03:48
Has anyone gotten typegoose to run in prod and aot 

ng build --prod --aot

this issue was closed
the feedback from the team is negative
https://github.com/angular/angular/issues/25684

and they are unlikely to go deep into the compiler enough to get this working like it should

I have made a few forked attempts to modify hooks.ts to no avail

if anyone can take a look or make a stab at this that would be terrific

unable to get load time down without minified build or even release anything

your help is appreciated

**Comment by nhhockeyplayer** [comment] 2018-10-21 14:03
I would be happy to pay someone to fix this

**Comment by hasezoey** [comment] 2019-09-14 18:13
Duplicate of #138 

@Ben305 this can be closed

**Closed** 2019-09-14 20:04 UTC
