### ISSUE TITLE
how can i add a instanceMethod for array?

### ISSUE THREAD

**Issue by halleyxu** [szokodiakos/typegoose#30] opened 2017-08-30 09:12 UTC
just like in demo user.ts	

@instanceMethod
addJob(this: InstanceType<User>) {
	this.previousJobs.push({ title: 'Janitor'});
	this.save();
}

i got error.

**Comment by szokodiakos** [comment] 2017-09-07 09:22
Hello! What kind of error do you get, and can you please include your whole file?

**Comment by halleyxu** [comment] 2017-09-08 08:35
thanks for replay~
the error print with webstrom is 
Error:(86, 26) TS2345:Argument of type '{ title: string; }' is not assignable to parameter of type 'Job'.
  Property 'startedAt' is missing in type '{ title: string; }'.

if add {id:"",getModelForClass:null} the error disappear

this.previousJobs.push({ title: 'Janitor',id:"",getModelForClass:null});      noerror
this.previousJobs.push({ title: 'Janitor'});                                                     error

**Comment by szokodiakos** [comment] 2017-09-11 08:42
I think the problem is that you forgot to pass the template parameter to `InstanceType`: `InstanceType<User>`. Let me know if this fixes the error

**Comment by halleyxu** [comment] 2017-09-11 09:13
@instanceMethod
addJob(this: InstanceType<User>) {
	this.previousJobs.push({startedAt:new Date(),id:"xx",getModelForClass:null});
	this.save();
}

need add "id:"xx",getModelForClass:null" it's about class Job and InstanceType <User> does not matter

**Comment by szokodiakos** [comment] 2017-09-12 07:06
Okay i will try to reproduce the problem.

**Comment by vinczedani** [comment] 2017-09-19 14:20
Hi @halleyxu 
I looked into your issue. Based on your report I changed the "demo" code for the tests. We had some issue on a typescript level that mad the Job interface require the getModelForClass and the startedAt.
Please look at the files changed [here](https://github.com/szokodiakos/typegoose/pull/37/files)
The main changes are that the typegoose extend is removed from subDocument (this caused the getModelForClass requirement) and the '?' mark on the typeScript definition of the Job class (this made startedAt required when pushing it to Job array). But please note that this way on the Job subClass you wont be able to create instanceMethods or staticMethods.
I hope it helps. If you feel like this answer resolved your question please close the issue.
If you have any more question feel free to ask it.
Thanks,
Daniel

**Closed** 2017-09-20 13:10 UTC
Labels: question
