### ISSUE TITLE
Error when using @arrayProp such that it's impossible to store nested ObjectID refs

### ISSUE THREAD

**Issue by nicky-lenaers** [szokodiakos/typegoose#200] opened 2018-09-17 15:56 UTC
I have an `@arrayProp` decorator that should store a list of objects. Each object contains a property `project` and a property `role`. See:

```ts
@arrayProp({
  items: {
    project: ProjectSchema,
    role: Object.values(ProjectRoleTypes)
  }
})
public projects: {
  project: Ref<ProjectSchema>,
  role: ProjectRole
}[];
```

This fails with:

```sh
C:\...\node_modules\typegoose\lib\prop.js:64
    const instance = new Type();
                     ^

TypeError: Type is not a constructor
```

I tried working around it, by replacing the `items`:

```ts
import { Schema } from 'mongoose';

@arrayProp({
  _id: false,
   items: Schema.Types.Array // <-- this line
})
public projects: {
  project: Ref<ProjectSchema>,
  role: ProjectRole
}[];
```

This at least compiles, but for some reason it ends up being a `Mixed` Type instead of `Array` Type, preventing me from storing the `ObjectID` references properly:

```sh
projects Mixed {
  path: 'projects',
  instance: 'Mixed',
  validators: [],
  setters: [],
  getters: [],
  options: { '0': {}, _id: false, type: [Function: Object] },
  _index: null }
```

Is there a way to achieve the nested ObjectID references inside arrays?

**Comment by hasezoey** [comment] 2019-07-31 17:24
Duplicate of #54 

@Ben305

**Closed** 2019-07-31 17:28 UTC
