### ISSUE TITLE
typegoose together with plugin Mongoosastic

### ISSUE THREAD

**Issue by andreas-engman** [szokodiakos/typegoose#119] opened 2018-03-14 08:27 UTC
Mongoosastic is a mongoose plugin that can automatically index your models into elasticsearch. However, it does not seem that you can set custom properites with typegoose. Example of what I want to achieve:

```
import { plugin, prop, Typegoose, ModelType, InstanceType } from 'typegoose';
import * as mongoosastic from 'mongoosastic';

@plugin(mongoosastic)
export class SomeTest extends Typegoose {
	@prop({ required: true, unique: true, es_indexed: true })
	someProperty: string;

	@prop({ es_indexed: false })
	someOtherPropery: string;
}
````

How should I go by setting custom properties for plugins, in this case (for example) es_indexed?

**Comment by renehauck** [comment] 2018-05-06 10:40
also have problems with this

**Comment by renehauck** [comment] 2018-05-07 13:42
the problem is not this awesome plugin, the problem is mongoosastic. It doesn't work with elasticsearch 6. The props, for example "es_indexed" is presented in the plugin itself.

For me, this issue should be closed

**Comment by hasezoey** [comment] 2019-08-07 18:08
@Ben305  this can be closed in favor of https://github.com/szokodiakos/typegoose/issues/374#issuecomment-519026965

**Comment by hasezoey** [comment] 2019-09-20 10:52
@Ben305 Bump to close

**Closed** 2019-09-20 12:50 UTC
