### ISSUE TITLE
a bug of extends

### ISSUE THREAD

**Issue by aoi-umi** [szokodiakos/typegoose#182] opened 2018-08-22 08:41 UTC
```
class BaseUser extends Typegoose {
    @prop()
    name?: string;
    @instanceMethod
    a() {
        console.log('a, base');
    }
}
class User extends BaseUser {
    @prop({
        required: false,
    })
    name?: string;
    @instanceMethod
    a() {
        console.log('a, user 1');
    }
}

class User2 extends BaseUser {
    @prop({
        required: false,
    })
    name?: string;
    @instanceMethod
    b() {
        console.log('b, user 2');
    }
}


const UserModel = new User().getModelForClass(User);
const UserModel2 = new User2().getModelForClass(User2);

--------------------------------------
let u = await UserModel.findOne();
    console.log(u);
    if (u != null)
        u.a();
    let u2 = await UserModel2.findOne();
    console.log(u2);
    if (u2 != null)
        u2.a(), u2.b();

finally get this:
a, user 1
a, user 1
b, user 2
```

**Comment by hasezoey** [comment] 2019-07-27 21:35
tested using
```ts
import * as mongoose from "mongoose";
import { instanceMethod, isDocument, prop, Ref, Typegoose } from "./typegoose/src/typegoose";

class Base extends Typegoose {
    @prop()
    public name: string;

    @instanceMethod
    public a() {
        console.log("a, base");
    }
}

class A1 extends Base {
    @instanceMethod
    public a() {
        console.log("a, a1");
    }
}

class A2 extends Base {
    @instanceMethod
    public b() {
        console.log("a, a2");
    }
}

const BaseModel = new Base().getModelForClass(Base);
const A1Model = new A1().getModelForClass(A1);
const A2Model = new A2().getModelForClass(A2);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify182",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const base = await BaseModel.create({ name: "base" } as Partial<Base>);
    const ia1 = await A1Model.create({ name: "a1" } as A1);
    const ia2 = await A2Model.create({ name: "a2" } as Partial<A2>);

    base.a();
    ia1.a();
    ia2.a();
    ia2.b();

    await mongoose.disconnect();
})();
```

with log (excluding the mongoose inserts)
```
a, base
a, a1
a, a1
b, a2
```

so it is confirmed

@Ben305 could you add label "bug"?

**Comment by hasezoey** [comment] 2019-08-07 18:03
this got fixed by the rework of 6.0.0 (since 6.0.0-14)

**Comment by hasezoey** [comment] 2019-09-10 05:57
@Ben305 Bump to close

**Comment by hasezoey** [comment] 2019-09-20 11:13
@Ben305 Bump to close

**Closed** 2019-09-20 12:49 UTC
